// <auto-generated />
using System;
using ContextLayer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContextLayer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ContextLayerDbContext))]
    [Migration("20260511144123_OnboardingApplications")]
    partial class OnboardingApplications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContextLayer.Domain.Entities.AgentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<Guid>("ContextSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OutputJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("PromptTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProvenanceJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SalesObjective")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContextSnapshotId");

                    b.HasIndex("PromptTemplateId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("agent_runs", (string)null);
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CreatedAtUtc");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.ConnectorCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectorType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProtectedValue")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SecretReference")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("SecretReference")
                        .IsUnique();

                    b.HasIndex("TenantId", "DataSourceId", "SecretKey")
                        .IsUnique();

                    b.ToTable("connector_credentials", (string)null);
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.ContextFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttributeKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<Guid>("ContextSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("FreshUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProvenanceJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("SemanticAttributeDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceSelectorDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("ValueType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SemanticAttributeDefinitionId");

                    b.HasIndex("SourceSelectorDefinitionId");

                    b.HasIndex("ContextSnapshotId", "AttributeKey")
                        .IsUnique();

                    b.ToTable("context_facts", (string)null);
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.ContextSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsStale")
                        .HasColumnType("boolean");

                    b.Property<decimal>("OverallConfidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<int>("SnapshotVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("TenantId", "UserProfileId", "GeneratedAtUtc");

                    b.ToTable("context_snapshots", (string)null);
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.DataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastSuccessfulSyncAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("data_sources", (string)null);
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.OperatorAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("operator_accounts", (string)null);
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.PromptTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DeveloperPrompt")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("GuardrailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OutputSchemaJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserPromptTemplate")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("prompt_templates", (string)null);
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.ProvenanceMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContextFactId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SelectorExecutionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceRecordKey")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContextFactId");

                    b.HasIndex("SelectorExecutionId");

                    b.HasIndex("TenantId", "Kind", "ObservedAtUtc");

                    b.ToTable("provenance_metadata", (string)null);
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.RecomputeJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SelectorExecutionCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("TenantId", "CorrelationId")
                        .IsUnique();

                    b.ToTable("recompute_jobs", (string)null);
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.SelectorDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DataSourceId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DefaultConfidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ExplanationTemplate")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ExpressionJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("FreshnessWindowMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("MappingKind")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ScheduleIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetAttributeDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValidationSchemaJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("TargetAttributeDefinitionId");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("selector_definitions", (string)null);
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.SelectorExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("ExecutionMode")
                        .HasColumnType("integer");

                    b.Property<string>("PipelineTraceJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RawSourceDataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ResultConfidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<string>("ResultExplanation")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ResultObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResultProvenanceJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ResultValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("ResultValueType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SelectorDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValidationErrorsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("SelectorDefinitionId");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("TenantId", "CorrelationId");

                    b.ToTable("selector_executions", (string)null);
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.SemanticAttributeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DataType")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ExampleValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique();

                    b.ToTable("semantic_attribute_definitions", (string)null);
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ExternalUserId")
                        .IsUnique();

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.UserSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DataSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProvenanceJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("ValueType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("TenantId", "UserProfileId", "Key", "ObservedAtUtc");

                    b.ToTable("user_signals", (string)null);
                });

            modelBuilder.Entity("ContextLayer.Domain.Saas.ApiClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RotatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScopesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.HasIndex("WorkspaceId");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("saas_api_clients", (string)null);
                });

            modelBuilder.Entity("ContextLayer.Domain.Saas.BillingUsageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DimensionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Metric")
                        .HasColumnType("integer");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("WindowEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("WindowStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.HasIndex("TenantId", "Metric", "WindowStartUtc");

                    b.ToTable("saas_billing_usage_records", (string)null);
                });

            modelBuilder.Entity("ContextLayer.Domain.Saas.ConnectorInstallation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ConnectorType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("HealthJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("LastCheckedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("WorkspaceId");

                    b.HasIndex("TenantId", "WorkspaceId", "DataSourceId")
                        .IsUnique();

                    b.ToTable("saas_connector_installations", (string)null);
                });

            modelBuilder.Entity("ContextLayer.Domain.Saas.ContextPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("ContextSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryChannelsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ManifestJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PackageKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContextSnapshotId");

                    b.HasIndex("TenantId", "PackageKey")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "GeneratedAtUtc");

                    b.ToTable("saas_context_packages", (string)null);
                });

            modelBuilder.Entity("ContextLayer.Domain.Saas.OnboardingApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AdminEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid?>("AdminOperatorAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("AiUseCasesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataCategoriesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("IntendedUseCase")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("NextStepsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("OrganisationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PiiSensitivityLevel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("PreferredDeploymentMode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("PrimaryWorkspaceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceSystemsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenantSlug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AdminOperatorAccountId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantSlug");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("saas_onboarding_applications", (string)null);
                });

            modelBuilder.Entity("ContextLayer.Domain.Saas.OnboardingState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StepKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.HasIndex("TenantId", "WorkspaceId", "StepKey")
                        .IsUnique();

                    b.ToTable("saas_onboarding_states", (string)null);
                });

            modelBuilder.Entity("ContextLayer.Domain.Saas.TenantSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BillingCustomerReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CurrentPeriodEndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntitlementsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Plan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("TrialEndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("saas_tenant_subscriptions", (string)null);
                });

            modelBuilder.Entity("ContextLayer.Domain.Saas.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IsDefault");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique();

                    b.ToTable("saas_workspaces", (string)null);
                });

            modelBuilder.Entity("ContextLayer.Domain.Saas.WorkspaceMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("InvitedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OperatorAccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OperatorAccountId");

                    b.HasIndex("WorkspaceId");

                    b.HasIndex("TenantId", "WorkspaceId", "OperatorAccountId")
                        .IsUnique();

                    b.ToTable("saas_workspace_members", (string)null);
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.AgentRun", b =>
                {
                    b.HasOne("ContextLayer.Domain.Entities.ContextSnapshot", "ContextSnapshot")
                        .WithMany("AgentRuns")
                        .HasForeignKey("ContextSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ContextLayer.Domain.Entities.PromptTemplate", "PromptTemplate")
                        .WithMany("AgentRuns")
                        .HasForeignKey("PromptTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ContextLayer.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContextSnapshot");

                    b.Navigation("PromptTemplate");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.ConnectorCredential", b =>
                {
                    b.HasOne("ContextLayer.Domain.Entities.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.ContextFact", b =>
                {
                    b.HasOne("ContextLayer.Domain.Entities.ContextSnapshot", "ContextSnapshot")
                        .WithMany("Facts")
                        .HasForeignKey("ContextSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContextLayer.Domain.Entities.SemanticAttributeDefinition", "SemanticAttributeDefinition")
                        .WithMany()
                        .HasForeignKey("SemanticAttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ContextLayer.Domain.Entities.SelectorDefinition", "SourceSelectorDefinition")
                        .WithMany()
                        .HasForeignKey("SourceSelectorDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContextSnapshot");

                    b.Navigation("SemanticAttributeDefinition");

                    b.Navigation("SourceSelectorDefinition");
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.ContextSnapshot", b =>
                {
                    b.HasOne("ContextLayer.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("ContextSnapshots")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.DataSource", b =>
                {
                    b.HasOne("ContextLayer.Domain.Entities.Tenant", "Tenant")
                        .WithMany("DataSources")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.OperatorAccount", b =>
                {
                    b.HasOne("ContextLayer.Domain.Entities.Tenant", "Tenant")
                        .WithMany("OperatorAccounts")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.PromptTemplate", b =>
                {
                    b.HasOne("ContextLayer.Domain.Entities.Tenant", "Tenant")
                        .WithMany("PromptTemplates")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.ProvenanceMetadata", b =>
                {
                    b.HasOne("ContextLayer.Domain.Entities.ContextFact", "ContextFact")
                        .WithMany()
                        .HasForeignKey("ContextFactId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ContextLayer.Domain.Entities.SelectorExecution", "SelectorExecution")
                        .WithMany()
                        .HasForeignKey("SelectorExecutionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ContextFact");

                    b.Navigation("SelectorExecution");
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.RecomputeJob", b =>
                {
                    b.HasOne("ContextLayer.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.SelectorDefinition", b =>
                {
                    b.HasOne("ContextLayer.Domain.Entities.DataSource", "DataSource")
                        .WithMany("SelectorDefinitions")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ContextLayer.Domain.Entities.SemanticAttributeDefinition", "TargetAttributeDefinition")
                        .WithMany("SelectorDefinitions")
                        .HasForeignKey("TargetAttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ContextLayer.Domain.Entities.Tenant", "Tenant")
                        .WithMany("SelectorDefinitions")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");

                    b.Navigation("TargetAttributeDefinition");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.SelectorExecution", b =>
                {
                    b.HasOne("ContextLayer.Domain.Entities.SelectorDefinition", "SelectorDefinition")
                        .WithMany("Executions")
                        .HasForeignKey("SelectorDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContextLayer.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SelectorDefinition");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.SemanticAttributeDefinition", b =>
                {
                    b.HasOne("ContextLayer.Domain.Entities.Tenant", "Tenant")
                        .WithMany("SemanticAttributes")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("ContextLayer.Domain.Entities.Tenant", "Tenant")
                        .WithMany("UserProfiles")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.UserSignal", b =>
                {
                    b.HasOne("ContextLayer.Domain.Entities.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ContextLayer.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("Signals")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("ContextLayer.Domain.Saas.ApiClient", b =>
                {
                    b.HasOne("ContextLayer.Domain.Entities.Tenant", "Tenant")
                        .WithMany("ApiClients")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContextLayer.Domain.Saas.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Tenant");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ContextLayer.Domain.Saas.BillingUsageRecord", b =>
                {
                    b.HasOne("ContextLayer.Domain.Entities.Tenant", "Tenant")
                        .WithMany("BillingUsageRecords")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContextLayer.Domain.Saas.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Tenant");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ContextLayer.Domain.Saas.ConnectorInstallation", b =>
                {
                    b.HasOne("ContextLayer.Domain.Entities.DataSource", "DataSource")
                        .WithMany("ConnectorInstallations")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContextLayer.Domain.Saas.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ContextLayer.Domain.Saas.ContextPackage", b =>
                {
                    b.HasOne("ContextLayer.Domain.Entities.ContextSnapshot", "ContextSnapshot")
                        .WithMany("ContextPackages")
                        .HasForeignKey("ContextSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContextLayer.Domain.Saas.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContextSnapshot");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ContextLayer.Domain.Saas.OnboardingApplication", b =>
                {
                    b.HasOne("ContextLayer.Domain.Entities.OperatorAccount", "AdminOperatorAccount")
                        .WithMany()
                        .HasForeignKey("AdminOperatorAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ContextLayer.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ContextLayer.Domain.Saas.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AdminOperatorAccount");

                    b.Navigation("Tenant");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ContextLayer.Domain.Saas.OnboardingState", b =>
                {
                    b.HasOne("ContextLayer.Domain.Saas.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ContextLayer.Domain.Saas.TenantSubscription", b =>
                {
                    b.HasOne("ContextLayer.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Subscriptions")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ContextLayer.Domain.Saas.Workspace", b =>
                {
                    b.HasOne("ContextLayer.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Workspaces")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ContextLayer.Domain.Saas.WorkspaceMember", b =>
                {
                    b.HasOne("ContextLayer.Domain.Entities.OperatorAccount", "OperatorAccount")
                        .WithMany("WorkspaceMemberships")
                        .HasForeignKey("OperatorAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContextLayer.Domain.Saas.Workspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperatorAccount");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.ContextSnapshot", b =>
                {
                    b.Navigation("AgentRuns");

                    b.Navigation("ContextPackages");

                    b.Navigation("Facts");
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.DataSource", b =>
                {
                    b.Navigation("ConnectorInstallations");

                    b.Navigation("SelectorDefinitions");
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.OperatorAccount", b =>
                {
                    b.Navigation("WorkspaceMemberships");
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.PromptTemplate", b =>
                {
                    b.Navigation("AgentRuns");
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.SelectorDefinition", b =>
                {
                    b.Navigation("Executions");
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.SemanticAttributeDefinition", b =>
                {
                    b.Navigation("SelectorDefinitions");
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("ApiClients");

                    b.Navigation("BillingUsageRecords");

                    b.Navigation("DataSources");

                    b.Navigation("OperatorAccounts");

                    b.Navigation("PromptTemplates");

                    b.Navigation("SelectorDefinitions");

                    b.Navigation("SemanticAttributes");

                    b.Navigation("Subscriptions");

                    b.Navigation("UserProfiles");

                    b.Navigation("Workspaces");
                });

            modelBuilder.Entity("ContextLayer.Domain.Entities.UserProfile", b =>
                {
                    b.Navigation("ContextSnapshots");

                    b.Navigation("Signals");
                });

            modelBuilder.Entity("ContextLayer.Domain.Saas.Workspace", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
