// <auto-generated />
using System;
using KynticAI.Scout.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KynticAI.Scout.Infrastructure.Persistence.CustomerOpsMigrations
{
    [DbContext(typeof(CustomerOpsDbContext))]
    [Migration("20260509192326_CustomerOpsInitialCreate")]
    partial class CustomerOpsInitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.BillingMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AnnualRecurringRevenue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("BillingStatus")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerOpsTenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("DaysPastDue")
                        .HasColumnType("integer");

                    b.Property<int>("ExpansionSeatDelta")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MetricDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MonthlyRecurringRevenue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("PaymentFailures30d")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerAccountId");

                    b.HasIndex("CustomerOpsTenantId", "MetricDateUtc");

                    b.ToTable("billing_metrics", (string)null);
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.CustomerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountOwner")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("AnnualRevenue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerOpsTenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("EmployeeCount")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalAccountId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("LifecycleStage")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerOpsTenantId", "Domain")
                        .IsUnique();

                    b.HasIndex("CustomerOpsTenantId", "ExternalAccountId")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.CustomerContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerOpsTenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ExternalContactId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDecisionMaker")
                        .HasColumnType("boolean");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PreferredChannel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerAccountId");

                    b.HasIndex("CustomerOpsTenantId", "ExternalContactId")
                        .IsUnique();

                    b.HasIndex("CustomerOpsTenantId", "ExternalUserId");

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.CustomerContactSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerOpsTenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DecisionMakerLikelihood")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("decision_maker_likelihood");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_user_id");

                    b.Property<DateTime>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at_utc");

                    b.Property<string>("PreferredChannel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("preferred_channel");

                    b.Property<string>("StakeholderSeniority")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stakeholder_seniority");

                    b.Property<string>("TenantSlug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_slug");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerOpsTenantId", "ExternalUserId")
                        .IsUnique();

                    b.ToTable("customer_contact_signals", (string)null);
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.CustomerContextRollup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveDays30")
                        .HasColumnType("integer")
                        .HasColumnName("active_days_30");

                    b.Property<int>("ActivityScore")
                        .HasColumnType("integer")
                        .HasColumnName("activity_score");

                    b.Property<int>("AutomationRuns30")
                        .HasColumnType("integer")
                        .HasColumnName("automation_runs_30");

                    b.Property<int>("BudgetReadinessScore")
                        .HasColumnType("integer")
                        .HasColumnName("budget_readiness_score");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerOpsTenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("DaysPastDue")
                        .HasColumnType("integer")
                        .HasColumnName("days_past_due");

                    b.Property<int>("EnterpriseInterestScore")
                        .HasColumnType("integer")
                        .HasColumnName("enterprise_interest_score");

                    b.Property<int>("ExpansionSeatDelta")
                        .HasColumnType("integer")
                        .HasColumnName("expansion_seat_delta");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_user_id");

                    b.Property<int>("FeatureAdoptionScore")
                        .HasColumnType("integer")
                        .HasColumnName("feature_adoption_score");

                    b.Property<int>("LatestSatisfactionScore")
                        .HasColumnType("integer")
                        .HasColumnName("latest_satisfaction_score");

                    b.Property<decimal>("MonthlyRecurringRevenue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monthly_recurring_revenue");

                    b.Property<DateTime>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at_utc");

                    b.Property<int>("OpenOpportunityProbability")
                        .HasColumnType("integer")
                        .HasColumnName("open_opportunity_probability");

                    b.Property<int>("OpenSupportTickets30")
                        .HasColumnType("integer")
                        .HasColumnName("open_support_tickets_30");

                    b.Property<int>("PaymentFailures30")
                        .HasColumnType("integer")
                        .HasColumnName("payment_failures_30");

                    b.Property<string>("PlanInterestSignal")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("plan_interest_signal");

                    b.Property<int>("PricingPageVisits30")
                        .HasColumnType("integer")
                        .HasColumnName("pricing_page_visits_30");

                    b.Property<int>("ProductFitScore")
                        .HasColumnType("integer")
                        .HasColumnName("product_fit_score");

                    b.Property<string>("RecentFeatureAdoptionSignal")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("recent_feature_adoption_signal");

                    b.Property<int>("RecentSalesActivityScore")
                        .HasColumnType("integer")
                        .HasColumnName("recent_sales_activity_score");

                    b.Property<string>("RecommendedSalesMotionSignal")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("recommended_sales_motion_signal");

                    b.Property<int>("SalesUrgencyScore")
                        .HasColumnType("integer")
                        .HasColumnName("sales_urgency_score");

                    b.Property<decimal>("SeatUtilizationRatio")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("seat_utilization_ratio");

                    b.Property<int>("SevereOpenTickets30")
                        .HasColumnType("integer")
                        .HasColumnName("severe_open_tickets_30");

                    b.Property<int>("SupportDragScore")
                        .HasColumnType("integer")
                        .HasColumnName("support_drag_score");

                    b.Property<string>("TenantSlug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_slug");

                    b.Property<bool>("TrialActivatedRecently")
                        .HasColumnType("boolean")
                        .HasColumnName("trial_activated_recently");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerOpsTenantId", "ExternalUserId")
                        .IsUnique();

                    b.ToTable("customer_context_rollups", (string)null);
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.CustomerEmailSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerOpsTenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("EmailClickCount30d")
                        .HasColumnType("integer")
                        .HasColumnName("email_click_count_30d");

                    b.Property<int>("EmailOpenCount30d")
                        .HasColumnType("integer")
                        .HasColumnName("email_open_count_30d");

                    b.Property<int>("EmailReplyCount30d")
                        .HasColumnType("integer")
                        .HasColumnName("email_reply_count_30d");

                    b.Property<string>("EngagementChannelSignal")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("engagement_channel_signal");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_user_id");

                    b.Property<DateTime>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at_utc");

                    b.Property<string>("TenantSlug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_slug");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerOpsTenantId", "ExternalUserId")
                        .IsUnique();

                    b.ToTable("customer_email_signals", (string)null);
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.CustomerOpsTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("customer_ops_tenants", (string)null);
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.CustomerSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerOpsTenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalSubscriptionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("MonthlyRecurringRevenue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProductCatalogItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RenewalAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SeatsPurchased")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime?>("TrialEndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerAccountId");

                    b.HasIndex("ProductCatalogItemId");

                    b.HasIndex("ProductPlanId");

                    b.HasIndex("CustomerOpsTenantId", "ExternalSubscriptionId")
                        .IsUnique();

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.CustomerUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerContactId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerOpsTenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsTrialUser")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkspaceRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerAccountId");

                    b.HasIndex("CustomerContactId");

                    b.HasIndex("CustomerOpsTenantId", "ExternalUserId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.EmailEngagementEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CampaignName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerContactId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerOpsTenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerContactId");

                    b.HasIndex("CustomerOpsTenantId", "OccurredAtUtc");

                    b.ToTable("email_engagement_events", (string)null);
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.ProductCatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.ProductPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AnnualPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IncludedSeats")
                        .HasColumnType("integer");

                    b.Property<decimal>("MonthlyPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProductCatalogItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ProductCatalogItemId");

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.ProductUsageSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveDays30")
                        .HasColumnType("integer");

                    b.Property<int>("AutomationRuns30d")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerContactId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerOpsTenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("FeatureAdoptionScore")
                        .HasColumnType("integer");

                    b.Property<int>("KeyFeatureEvents7d")
                        .HasColumnType("integer");

                    b.Property<int>("PricingPageVisits30d")
                        .HasColumnType("integer");

                    b.Property<int>("SeatsPurchased")
                        .HasColumnType("integer");

                    b.Property<int>("SeatsUsed")
                        .HasColumnType("integer");

                    b.Property<int>("Sessions7d")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SummaryDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerAccountId");

                    b.HasIndex("CustomerContactId");

                    b.HasIndex("CustomerOpsTenantId", "SummaryDateUtc");

                    b.HasIndex("CustomerOpsTenantId", "CustomerContactId", "SummaryDateUtc");

                    b.ToTable("product_usage_summaries", (string)null);
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.SalesActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerContactId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerOpsTenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerAccountId");

                    b.HasIndex("CustomerContactId");

                    b.HasIndex("CustomerOpsTenantId", "OccurredAtUtc");

                    b.ToTable("sales_activities", (string)null);
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.SalesOpportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CloseDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerContactId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerOpsTenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalOpportunityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OpportunityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("ProbabilityPercent")
                        .HasColumnType("integer");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerAccountId");

                    b.HasIndex("CustomerContactId");

                    b.HasIndex("CustomerOpsTenantId", "ExternalOpportunityId")
                        .IsUnique();

                    b.ToTable("opportunities", (string)null);
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.SupportTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerContactId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerOpsTenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalTicketId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("OpenedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SatisfactionScore")
                        .HasColumnType("integer");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerAccountId");

                    b.HasIndex("CustomerContactId");

                    b.HasIndex("CustomerOpsTenantId", "ExternalTicketId")
                        .IsUnique();

                    b.HasIndex("CustomerOpsTenantId", "Status");

                    b.ToTable("support_tickets", (string)null);
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.WebConversionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Campaign")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerContactId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerOpsTenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("IntentScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Page")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Referrer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerAccountId");

                    b.HasIndex("CustomerContactId");

                    b.HasIndex("CustomerOpsTenantId", "OccurredAtUtc");

                    b.ToTable("web_conversion_events", (string)null);
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.BillingMetric", b =>
                {
                    b.HasOne("KynticAI.Scout.Domain.Entities.CustomerAccount", "Account")
                        .WithMany("BillingMetrics")
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KynticAI.Scout.Domain.Entities.CustomerOpsTenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("CustomerOpsTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.CustomerAccount", b =>
                {
                    b.HasOne("KynticAI.Scout.Domain.Entities.CustomerOpsTenant", "Tenant")
                        .WithMany("Accounts")
                        .HasForeignKey("CustomerOpsTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.CustomerContact", b =>
                {
                    b.HasOne("KynticAI.Scout.Domain.Entities.CustomerAccount", "Account")
                        .WithMany("Contacts")
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KynticAI.Scout.Domain.Entities.CustomerOpsTenant", "Tenant")
                        .WithMany("Contacts")
                        .HasForeignKey("CustomerOpsTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.CustomerSubscription", b =>
                {
                    b.HasOne("KynticAI.Scout.Domain.Entities.CustomerAccount", "Account")
                        .WithMany("Subscriptions")
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KynticAI.Scout.Domain.Entities.CustomerOpsTenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("CustomerOpsTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KynticAI.Scout.Domain.Entities.ProductCatalogItem", "ProductCatalogItem")
                        .WithMany()
                        .HasForeignKey("ProductCatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KynticAI.Scout.Domain.Entities.ProductPlan", "ProductPlan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ProductPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("ProductCatalogItem");

                    b.Navigation("ProductPlan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.CustomerUser", b =>
                {
                    b.HasOne("KynticAI.Scout.Domain.Entities.CustomerAccount", "Account")
                        .WithMany("Users")
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KynticAI.Scout.Domain.Entities.CustomerContact", "Contact")
                        .WithMany("Users")
                        .HasForeignKey("CustomerContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KynticAI.Scout.Domain.Entities.CustomerOpsTenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("CustomerOpsTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Contact");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.EmailEngagementEvent", b =>
                {
                    b.HasOne("KynticAI.Scout.Domain.Entities.CustomerContact", "Contact")
                        .WithMany("EmailEngagementEvents")
                        .HasForeignKey("CustomerContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KynticAI.Scout.Domain.Entities.CustomerOpsTenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("CustomerOpsTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.ProductPlan", b =>
                {
                    b.HasOne("KynticAI.Scout.Domain.Entities.ProductCatalogItem", "ProductCatalogItem")
                        .WithMany("Plans")
                        .HasForeignKey("ProductCatalogItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCatalogItem");
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.ProductUsageSummary", b =>
                {
                    b.HasOne("KynticAI.Scout.Domain.Entities.CustomerAccount", "Account")
                        .WithMany("ProductUsageSummaries")
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KynticAI.Scout.Domain.Entities.CustomerContact", "Contact")
                        .WithMany("ProductUsageSummaries")
                        .HasForeignKey("CustomerContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KynticAI.Scout.Domain.Entities.CustomerOpsTenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("CustomerOpsTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Contact");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.SalesActivity", b =>
                {
                    b.HasOne("KynticAI.Scout.Domain.Entities.CustomerAccount", "Account")
                        .WithMany("SalesActivities")
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KynticAI.Scout.Domain.Entities.CustomerContact", "Contact")
                        .WithMany("SalesActivities")
                        .HasForeignKey("CustomerContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KynticAI.Scout.Domain.Entities.CustomerOpsTenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("CustomerOpsTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Contact");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.SalesOpportunity", b =>
                {
                    b.HasOne("KynticAI.Scout.Domain.Entities.CustomerAccount", "Account")
                        .WithMany("Opportunities")
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KynticAI.Scout.Domain.Entities.CustomerContact", "Contact")
                        .WithMany("Opportunities")
                        .HasForeignKey("CustomerContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KynticAI.Scout.Domain.Entities.CustomerOpsTenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("CustomerOpsTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Contact");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.SupportTicket", b =>
                {
                    b.HasOne("KynticAI.Scout.Domain.Entities.CustomerAccount", "Account")
                        .WithMany("SupportTickets")
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KynticAI.Scout.Domain.Entities.CustomerContact", "Contact")
                        .WithMany("SupportTickets")
                        .HasForeignKey("CustomerContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KynticAI.Scout.Domain.Entities.CustomerOpsTenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("CustomerOpsTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Contact");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.WebConversionEvent", b =>
                {
                    b.HasOne("KynticAI.Scout.Domain.Entities.CustomerAccount", "Account")
                        .WithMany("WebConversionEvents")
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KynticAI.Scout.Domain.Entities.CustomerContact", "Contact")
                        .WithMany("WebConversionEvents")
                        .HasForeignKey("CustomerContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KynticAI.Scout.Domain.Entities.CustomerOpsTenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("CustomerOpsTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Contact");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.CustomerAccount", b =>
                {
                    b.Navigation("BillingMetrics");

                    b.Navigation("Contacts");

                    b.Navigation("Opportunities");

                    b.Navigation("ProductUsageSummaries");

                    b.Navigation("SalesActivities");

                    b.Navigation("Subscriptions");

                    b.Navigation("SupportTickets");

                    b.Navigation("Users");

                    b.Navigation("WebConversionEvents");
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.CustomerContact", b =>
                {
                    b.Navigation("EmailEngagementEvents");

                    b.Navigation("Opportunities");

                    b.Navigation("ProductUsageSummaries");

                    b.Navigation("SalesActivities");

                    b.Navigation("SupportTickets");

                    b.Navigation("Users");

                    b.Navigation("WebConversionEvents");
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.CustomerOpsTenant", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Contacts");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.ProductCatalogItem", b =>
                {
                    b.Navigation("Plans");
                });

            modelBuilder.Entity("KynticAI.Scout.Domain.Entities.ProductPlan", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
