#!/usr/bin/env sh
set -eu

RESET=false
NO_BUILD=false
NO_OPEN_REPORT=false

while [ "$#" -gt 0 ]; do
  case "$1" in
    --reset)
      RESET=true
      ;;
    --no-build)
      NO_BUILD=true
      ;;
    --no-open-report)
      NO_OPEN_REPORT=true
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 2
      ;;
  esac
  shift
done

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)

command -v docker >/dev/null 2>&1 || {
  echo "Required command 'docker' was not found in PATH." >&2
  exit 1
}

docker info >/dev/null 2>&1 || {
  echo "Docker is installed, but the Docker engine is not running. Start Docker Desktop or your Docker daemon and run this script again." >&2
  exit 1
}

cd "$REPO_ROOT"

if [ "$RESET" = "true" ]; then
  echo ">> docker compose down --remove-orphans -v"
  docker compose down --remove-orphans -v
fi

if [ "$NO_BUILD" = "true" ]; then
  echo ">> docker compose up -d"
  docker compose up -d
  BUILD_STATUS="Skipped by --no-build; existing Docker images were reused."
else
  echo ">> docker compose up -d --build"
  docker compose up -d --build
  BUILD_STATUS="Passed. Docker built the web image, including npm run build, and built the API image."
fi

wait_for_url() {
  url="$1"
  attempts="${2:-60}"
  attempt=1
  while [ "$attempt" -le "$attempts" ]; do
    if curl -fsS "$url" >/dev/null 2>&1; then
      return 0
    fi
    sleep 2
    attempt=$((attempt + 1))
  done

  echo "Timed out waiting for $url" >&2
  exit 1
}

wait_for_url "http://127.0.0.1:5198/health/ready"
wait_for_url "http://127.0.0.1:5173"

TOKEN=$(
  curl -fsS -X POST "http://127.0.0.1:5198/api/auth/login" \
    -H "Content-Type: application/json" \
    -d '{"tenantSlug":"demo","email":"admin@scout.local","password":"DemoAdmin123!"}' \
  | sed -n 's/.*"accessToken":"\([^"]*\)".*/\1/p'
)

CONTEXT=$(
  curl -fsS "http://127.0.0.1:5198/api/v1/context/users/123?tenantSlug=demo" \
    -H "Authorization: Bearer $TOKEN"
)

printf '%s' "$CONTEXT" | grep -q '"fullName"' || {
  echo "Startup smoke test failed: demo user 123 context was not returned." >&2
  exit 1
}

DEMO_USER=$(printf '%s' "$CONTEXT" | sed -n 's/.*"fullName":"\([^"]*\)".*/\1/p')
DEMO_COMPANY=$(printf '%s' "$CONTEXT" | sed -n 's/.*"companyName":"\([^"]*\)".*/\1/p')

CONNECTOR_CONFIG='{"scenario":"safe-local-demo","records":[{"externalUserId":"123","observedAtUtc":"2026-05-11T10:45:00Z","payload":{"crm":{"lifecycleStage":"customer","opportunityStage":"proposal","preferredChannel":"email"}}}]}'
CONNECTOR_CONFIG_ESC=$(printf '%s' "$CONNECTOR_CONFIG" | sed 's/\\/\\\\/g; s/"/\\"/g')
VALIDATE_BODY="{\"connectorType\":\"mockCrm\",\"kind\":1,\"configurationJson\":\"$CONNECTOR_CONFIG_ESC\",\"credentialsJson\":null}"
VALIDATE_RESPONSE=$(
  curl -fsS -X POST "http://127.0.0.1:5198/api/rest/connectors/validate" \
    -H "Authorization: Bearer $TOKEN" \
    -H "Content-Type: application/json" \
    -d "$VALIDATE_BODY"
)
printf '%s' "$VALIDATE_RESPONSE" | grep -q '"isValid":true' || {
  echo "Connector validation failed." >&2
  echo "$VALIDATE_RESPONSE" >&2
  exit 1
}

REGISTER_NAME="Mock CRM connector install smoke"
REGISTER_BODY="{\"id\":null,\"tenantSlug\":\"demo\",\"name\":\"$REGISTER_NAME\",\"description\":\"Safe connector smoke-test data source generated by the Docker start script.\",\"kind\":1,\"connectorType\":\"mockCrm\",\"configurationJson\":\"$CONNECTOR_CONFIG_ESC\",\"credentialsJson\":null}"
REGISTER_RESPONSE=$(
  curl -fsS -X POST "http://127.0.0.1:5198/api/rest/connectors/register" \
    -H "Authorization: Bearer $TOKEN" \
    -H "Content-Type: application/json" \
    -d "$REGISTER_BODY"
)
DATA_SOURCE_ID=$(printf '%s' "$REGISTER_RESPONSE" | sed -n 's/.*"dataSourceId":"\([^"]*\)".*/\1/p')
if [ -z "$DATA_SOURCE_ID" ]; then
  echo "Connector registration did not return dataSourceId." >&2
  echo "$REGISTER_RESPONSE" >&2
  exit 1
fi

HEALTH_BODY="{\"tenantSlug\":\"demo\",\"dataSourceId\":\"$DATA_SOURCE_ID\",\"externalUserId\":\"123\",\"mode\":\"preview\"}"
HEALTH_RESPONSE=$(
  curl -fsS -X POST "http://127.0.0.1:5198/api/rest/connectors/health" \
    -H "Authorization: Bearer $TOKEN" \
    -H "Content-Type: application/json" \
    -d "$HEALTH_BODY"
)
printf '%s' "$HEALTH_RESPONSE" | grep -q '"isHealthy":true' || {
  echo "Connector health check failed." >&2
  echo "$HEALTH_RESPONSE" >&2
  exit 1
}
CONNECTOR_HEALTH_STATUS=$(printf '%s' "$HEALTH_RESPONSE" | sed -n 's/.*"status":"\([^"]*\)".*/\1/p')

LOCAL_EVENT_ID="install-report-local-$(date +%Y%m%d%H%M%S)"
LOCAL_EVENT_BODY="{\"eventId\":\"$LOCAL_EVENT_ID\",\"sourceSystem\":\"customer_context_rollups\",\"eventType\":\"source.product_usage.rollup_ready\",\"externalUserId\":\"123\",\"externalAccountId\":\"acct-larkspur-logistics\",\"payload\":{\"active_days_30\":26,\"pricing_page_visits_30\":4,\"source\":\"install-report-local\"}}"
LOCAL_WEBHOOK_RESPONSE=$(
  curl -fsS -X POST "http://127.0.0.1:5198/api/v1/events/source-system?tenantSlug=demo" \
    -H "Authorization: Bearer $TOKEN" \
    -H "Content-Type: application/json" \
    -d "$LOCAL_EVENT_BODY"
)
LOCAL_WEBHOOK_STATUS=$(printf '%s' "$LOCAL_WEBHOOK_RESPONSE" | sed -n 's/.*"status":"\([^"]*\)".*/\1/p')
LOCAL_STORED_SIGNAL_COUNT=$(printf '%s' "$LOCAL_WEBHOOK_RESPONSE" | sed -n 's/.*"storedSignalCount":\([0-9][0-9]*\).*/\1/p')
LOCAL_MATCHED_SELECTOR_COUNT=$(printf '%s' "$LOCAL_WEBHOOK_RESPONSE" | sed -n 's/.*"matchedSelectorCount":\([0-9][0-9]*\).*/\1/p')

detect_lan_ip() {
  if command -v ip >/dev/null 2>&1; then
    ip route get 1.1.1.1 2>/dev/null | sed -n 's/.* src \([0-9.][0-9.]*\).*/\1/p' | sed -n '1p'
    return 0
  fi

  if command -v hostname >/dev/null 2>&1; then
    hostname -I 2>/dev/null | awk '{print $1}'
  fi
}

get_scout_bind_address() {
  if [ -n "${SCOUT_BIND_ADDRESS:-}" ]; then
    printf '%s\n' "$SCOUT_BIND_ADDRESS" | sed "s/^[\"']//;s/[\"']$//"
    return 0
  fi

  if [ -f "$REPO_ROOT/.env" ]; then
    ENV_BIND_ADDRESS=$(sed -n 's/^[[:space:]]*SCOUT_BIND_ADDRESS[[:space:]]*=[[:space:]]*//p' "$REPO_ROOT/.env" | sed -n '1p')
    if [ -n "$ENV_BIND_ADDRESS" ]; then
      printf '%s\n' "$ENV_BIND_ADDRESS" | sed "s/^[\"']//;s/[\"']$//"
      return 0
    fi
  fi

  printf '%s\n' "127.0.0.1"
}

is_lan_exposure_enabled() {
  NORMALISED_BIND=$(printf '%s' "${1:-127.0.0.1}" | sed "s/^[\"']//;s/[\"']$//" | tr '[:upper:]' '[:lower:]')
  case "$NORMALISED_BIND" in
    ""|"127.0.0.1"|"localhost"|"::1")
      return 1
      ;;
    *)
      return 0
      ;;
  esac
}

BIND_ADDRESS=$(get_scout_bind_address)
LAN_EXPOSURE_ENABLED=false
LAN_IP=""
if is_lan_exposure_enabled "$BIND_ADDRESS"; then
  LAN_EXPOSURE_ENABLED=true
  LAN_IP=$(detect_lan_ip || true)
fi
LAN_API_URL=""
LAN_WEBHOOK_STATUS=""
LAN_STORED_SIGNAL_COUNT=""
LAN_MATCHED_SELECTOR_COUNT=""
if [ "$LAN_EXPOSURE_ENABLED" = "true" ] && [ -n "$LAN_IP" ]; then
  LAN_API_URL="http://$LAN_IP:5198"
  if curl -fsS "$LAN_API_URL/health/ready" >/dev/null 2>&1; then
    LAN_EVENT_ID="install-report-lan-$(date +%Y%m%d%H%M%S)"
    LAN_EVENT_BODY="{\"eventId\":\"$LAN_EVENT_ID\",\"sourceSystem\":\"customer_context_rollups\",\"eventType\":\"source.product_usage.rollup_ready\",\"externalUserId\":\"123\",\"externalAccountId\":\"acct-larkspur-logistics\",\"payload\":{\"active_days_30\":26,\"pricing_page_visits_30\":4,\"source\":\"install-report-lan\"}}"
    LAN_WEBHOOK_RESPONSE=$(
      curl -fsS -X POST "$LAN_API_URL/api/v1/events/source-system?tenantSlug=demo" \
        -H "Authorization: Bearer $TOKEN" \
        -H "Content-Type: application/json" \
        -d "$LAN_EVENT_BODY" || true
    )
    LAN_WEBHOOK_STATUS=$(printf '%s' "$LAN_WEBHOOK_RESPONSE" | sed -n 's/.*"status":"\([^"]*\)".*/\1/p')
    LAN_STORED_SIGNAL_COUNT=$(printf '%s' "$LAN_WEBHOOK_RESPONSE" | sed -n 's/.*"storedSignalCount":\([0-9][0-9]*\).*/\1/p')
    LAN_MATCHED_SELECTOR_COUNT=$(printf '%s' "$LAN_WEBHOOK_RESPONSE" | sed -n 's/.*"matchedSelectorCount":\([0-9][0-9]*\).*/\1/p')
  fi
fi

REPORT_DIR="$REPO_ROOT/.local"
REPORT_PATH="$REPORT_DIR/scout-install-report.html"
mkdir -p "$REPORT_DIR"

if [ "$LAN_EXPOSURE_ENABLED" = "true" ] && [ -n "$LAN_IP" ]; then
  LAN_ROWS="<tr><th>LAN web</th><td><a href=\"http://$LAN_IP:5173\">http://$LAN_IP:5173</a></td></tr><tr><th>LAN API</th><td><a href=\"http://$LAN_IP:5198\">http://$LAN_IP:5198</a></td></tr><tr><th>LAN webhook</th><td><code>http://$LAN_IP:5198/api/v1/events/source-system?tenantSlug=demo</code></td></tr>"
else
  LAN_ROWS="<tr><th>Published bind address</th><td><code>$BIND_ADDRESS</code></td></tr><tr><th>LAN webhook</th><td>LAN exposure is disabled. Docker ports are bound to localhost by default; set <code>SCOUT_BIND_ADDRESS=0.0.0.0</code> only on a trusted LAN/VPN.</td></tr>"
fi

if [ -n "$LAN_WEBHOOK_STATUS" ]; then
  LAN_TEST="IP webhook test through <code>$LAN_API_URL</code>: event was <strong>$LAN_WEBHOOK_STATUS</strong>, stored <strong>$LAN_STORED_SIGNAL_COUNT</strong> signal, matched <strong>$LAN_MATCHED_SELECTOR_COUNT</strong> selectors."
elif [ "$LAN_EXPOSURE_ENABLED" != "true" ]; then
  LAN_TEST="LAN/IP webhook smoke was skipped because published Docker ports are bound to localhost by default."
else
  LAN_TEST="LAN/IP webhook smoke was skipped because no LAN IP was detected or the private address was not reachable from this host."
fi

if [ "$LAN_EXPOSURE_ENABLED" = "true" ] && [ -n "$LAN_IP" ]; then
  LAN_SUMMARY="printed LAN URL $LAN_IP."
else
  LAN_SUMMARY="kept LAN/private-network endpoints disabled; published bind address is <code>$BIND_ADDRESS</code>."
fi

cat > "$REPORT_PATH" <<EOF
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>KynticAI Scout Installation Report</title>
  <style>
    :root { --ink:#1f2320; --muted:#5f655f; --line:#d9ddd4; --paper:#f6f0e8; --panel:#ffffff; --copper:#b45f35; }
    body { margin:0; font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; background:var(--paper); color:var(--ink); }
    main { max-width:1120px; margin:0 auto; padding:34px 20px 54px; }
    header, section { border:1px solid var(--line); border-radius:22px; box-shadow:0 12px 30px rgba(31,35,32,.08); }
    header { display:grid; gap:14px; padding:28px; background:linear-gradient(135deg,#1f2320,#3a2d28); color:#fffaf4; }
    section { margin-top:18px; padding:24px; background:var(--panel); }
    h1 { margin:0; font-size:clamp(2rem,4vw,3.4rem); line-height:1; letter-spacing:0; }
    h2 { margin:0 0 14px; font-size:1.35rem; }
    p, li, td { line-height:1.6; color:var(--muted); }
    header p { color:#eadfd1; max-width:850px; }
    table { width:100%; border-collapse:collapse; }
    th, td { padding:12px 0; border-bottom:1px solid #ece7df; text-align:left; vertical-align:top; }
    th { width:220px; color:#394039; }
    a { color:#8f4b2a; font-weight:700; }
    code { display:inline-block; max-width:100%; overflow-wrap:anywhere; border-radius:10px; background:#1f2320; color:#fffaf4; padding:2px 7px; font-family:Consolas,monospace; font-size:.92em; }
    .badge { display:inline-flex; width:max-content; border-radius:999px; padding:5px 10px; font-size:.82rem; font-weight:800; background:#e4f0e1; color:#345a39; }
    .actions { display:flex; flex-wrap:wrap; gap:10px; margin-top:10px; }
    .actions a { display:inline-flex; text-decoration:none; border-radius:999px; padding:10px 14px; background:var(--copper); color:#fffaf4; }
    .actions a.secondary { background:#eef2ea; color:#314034; }
    .grid { display:grid; gap:14px; grid-template-columns:repeat(auto-fit,minmax(250px,1fr)); }
    .card { padding:16px; border:1px solid #e6ded3; border-radius:16px; background:#fffdf9; }
  </style>
</head>
<body>
  <main>
    <header>
      <div class="badge">Install self-test complete</div>
      <h1>KynticAI Scout is running locally</h1>
      <p>This report was generated by <code>scripts/start-scout-docker.sh</code> after Docker Compose started, the API became healthy, the demo context was queried, connectors were tested, and a source event was accepted.</p>
      <p>Generated at $(date '+%Y-%m-%d %H:%M:%S %z').</p>
      <div class="actions">
        <a href="http://127.0.0.1:5173">Open Scout web console</a>
        <a class="secondary" href="http://127.0.0.1:5198/api-docs">Open API docs</a>
        <a class="secondary" href="http://127.0.0.1:5173/data-sources">Open connector lab</a>
      </div>
    </header>

    <section>
      <h2>Verified on this laptop</h2>
      <ul>
        <li><strong>Build:</strong> $BUILD_STATUS</li>
        <li><strong>Docker stack:</strong> running; API and Postgres health checks are healthy.</li>
        <li><strong>Start script:</strong> $LAN_SUMMARY</li>
        <li><strong>Demo context:</strong> User 123 returned $DEMO_USER / $DEMO_COMPANY.</li>
        <li><strong>Connector test:</strong> mock CRM configuration validated, connector registered, health check returned $CONNECTOR_HEALTH_STATUS.</li>
        <li><strong>Local webhook test:</strong> event was $LOCAL_WEBHOOK_STATUS, stored $LOCAL_STORED_SIGNAL_COUNT signal, matched $LOCAL_MATCHED_SELECTOR_COUNT selectors.</li>
        <li>$LAN_TEST</li>
      </ul>
    </section>

    <section>
      <h2>Current running URLs</h2>
      <table>
        <tr><th>Web console</th><td><a href="http://127.0.0.1:5173">http://127.0.0.1:5173</a></td></tr>
        <tr><th>API</th><td><a href="http://127.0.0.1:5198">http://127.0.0.1:5198</a></td></tr>
        <tr><th>GraphQL</th><td><a href="http://127.0.0.1:5198/graphql">http://127.0.0.1:5198/graphql</a></td></tr>
        <tr><th>OpenAPI / Scalar</th><td><a href="http://127.0.0.1:5198/api-docs">http://127.0.0.1:5198/api-docs</a></td></tr>
        <tr><th>Grafana</th><td><a href="http://127.0.0.1:3000">http://127.0.0.1:3000</a> (<code>admin</code> / <code>admin</code>)</td></tr>
        <tr><th>Prometheus</th><td><a href="http://127.0.0.1:9090">http://127.0.0.1:9090</a></td></tr>
        $LAN_ROWS
      </table>
    </section>

    <section>
      <h2>Login</h2>
      <table>
        <tr><th>Tenant</th><td><code>demo</code></td></tr>
        <tr><th>Email</th><td><code>admin@scout.local</code></td></tr>
        <tr><th>Password</th><td><code>DemoAdmin123!</code></td></tr>
      </table>
    </section>

    <section>
      <h2>First walkthrough</h2>
      <ol>
        <li>Open <a href="http://127.0.0.1:5173/demo">/demo</a> for the executive story.</li>
        <li>Open <a href="http://127.0.0.1:5173/customers/123">/customers/123</a> for Avery Stone at Larkspur Logistics Group.</li>
        <li>Open <a href="http://127.0.0.1:5173/relationship-intelligence">/relationship-intelligence</a> to inspect exact linked records, relationships, citations, masking, and next action.</li>
        <li>Open <a href="http://127.0.0.1:5173/data-sources">/data-sources</a> to validate/register a connector, run health, and send a source event.</li>
        <li>Open <a href="http://127.0.0.1:5173/admin/events">/admin/events</a> to see source events and selector-triggered recomputation.</li>
        <li>Open <a href="http://127.0.0.1:5173/admin/connectors">/admin/connectors</a> to see executable open-core connectors versus enterprise/SaaS placeholders.</li>
      </ol>
    </section>

    <section>
      <h2>Webhook use</h2>
      <p>For local workshops, LAN/VPN testing, or static private IP installs, point source systems at the LAN webhook URL above. For public internet webhooks, use HTTPS with a stable DNS name or reverse proxy.</p>
      <p>Machine integrations should use an API client with <code>events:ingest</code> and webhook HMAC signing. The web console connector lab uses your logged-in admin token for a safe local smoke test.</p>
    </section>

    <section>
      <h2>Useful commands</h2>
      <div class="grid">
        <div class="card"><strong>Status</strong><p><code>docker compose ps</code></p></div>
        <div class="card"><strong>Logs</strong><p><code>docker compose logs -f api web</code></p></div>
        <div class="card"><strong>Stop</strong><p><code>docker compose down</code></p></div>
        <div class="card"><strong>Clean reset</strong><p><code>sh ./scripts/start-scout-docker.sh --reset</code></p></div>
        <div class="card"><strong>Upgrade</strong><p><code>git pull</code><br><code>sh ./scripts/start-scout-docker.sh</code></p></div>
      </div>
    </section>
  </main>
</body>
</html>
EOF

if [ "$NO_OPEN_REPORT" != "true" ]; then
  if command -v xdg-open >/dev/null 2>&1; then
    xdg-open "$REPORT_PATH" >/dev/null 2>&1 || true
  elif command -v open >/dev/null 2>&1; then
    open "$REPORT_PATH" >/dev/null 2>&1 || true
  elif command -v cmd.exe >/dev/null 2>&1; then
    if command -v cygpath >/dev/null 2>&1; then
      WIN_REPORT_PATH=$(cygpath -w "$REPORT_PATH")
    else
      WIN_REPORT_PATH="$REPORT_PATH"
    fi
    cmd.exe /C start "" "$WIN_REPORT_PATH" >/dev/null 2>&1 || true
  fi
fi

echo
echo "Scout Docker stack is running."
echo "Web app:      http://127.0.0.1:5173"
echo "API:          http://127.0.0.1:5198"
echo "GraphQL:      http://127.0.0.1:5198/graphql"
echo "OpenAPI:      http://127.0.0.1:5198/api-docs"
echo "Grafana:      http://127.0.0.1:3000"
echo "Prometheus:   http://127.0.0.1:9090"
if [ "$LAN_EXPOSURE_ENABLED" = "true" ] && [ -n "$LAN_IP" ]; then
  echo
  echo "LAN / private-network endpoints:"
  echo "LAN web app:  http://$LAN_IP:5173"
  echo "LAN API:      http://$LAN_IP:5198"
  echo "Webhook URL:  http://$LAN_IP:5198/api/v1/events/source-system?tenantSlug=demo"
  echo "Use the LAN webhook URL only on a trusted LAN/VPN, or put HTTPS/reverse-proxy/DNS in front of it."
else
  echo
  echo "LAN / private-network endpoints are disabled by default."
  echo "Published bind address: $BIND_ADDRESS"
  echo "Set SCOUT_BIND_ADDRESS=0.0.0.0 only when you intentionally expose the demo on a trusted LAN/VPN."
fi
echo
echo "Demo login:"
echo "  Tenant:   demo"
echo "  Email:    admin@scout.local"
echo "  Password: DemoAdmin123!"
echo
echo "Smoke test user: $DEMO_USER / $DEMO_COMPANY"
echo "Install report: $REPORT_PATH"
echo
docker compose ps
